// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Copy_textJs = require("../copy_text.js");
var Templates$LoginForm = require("../Templates.bs.js");
var HtmlConverter$LoginForm = require("../HtmlConverter.bs.js");

var defaultText = "<div style=\"font-weight: bolder\">Hello there! Go on &amp; convert your html!</div>";

var initialState_jsx = HtmlConverter$LoginForm.convert("__DEFAULT__", defaultText);

var initialState = {
  html: defaultText,
  jsx: initialState_jsx
};

function reducer(_state, action) {
  var str = action[0];
  return {
          html: str,
          jsx: HtmlConverter$LoginForm.convert("_INLINE_", str)
        };
}

function copy_text(prim) {
  Copy_textJs(prim);
  
}

function copyOutput(param) {
  Copy_textJs("copyMe");
  
}

function Index$default(Props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  return React.createElement("div", {
              className: "bg-gray-200 h-screen w-screen flex flex-col"
            }, Templates$LoginForm.header, React.createElement("div", {
                  className: "grid grid-cols-2 gap-4 mx-auto flex-1 px-4 mb-8 w-full"
                }, React.createElement("div", {
                      className: "bg-white overflow-hidden shadow rounded-lg border-yellow-400 border-b-2 shadow-lg",
                      id: "input"
                    }, React.createElement("div", {
                          className: "border-b-2 border-yellow-400 px-3 py-4 sm:px-6 bg-yellow-200 text-yellow-600"
                        }, React.createElement("h1", {
                              className: "text-lg font-bold"
                            }, "Paste HTML")), React.createElement("div", {
                          className: "p-1 h-full"
                        }, React.createElement("textarea", {
                              className: "w-full h-full p-4 outline-none focus:shadow-outline",
                              placeholder: "<div class=\"placeholder\">Paste something in here!</div>",
                              value: state.html,
                              onChange: (function (evt) {
                                  var v = evt.target.value;
                                  return Curry._1(dispatch, /* UpdateHTML */[v]);
                                })
                            }))), React.createElement("div", {
                      className: "bg-white overflow-hidden shadow rounded-lg border-red-400 border-b-2 shadow-lg",
                      id: "output"
                    }, React.createElement("div", {
                          className: "border-b-2 border-red-400 px-3 py-4 sm:px-6 bg-red-200 text-red-600 flex justify-between"
                        }, React.createElement("h1", {
                              className: "text-lg font-bold"
                            }, "Copy Reason"), React.createElement("button", {
                              onClick: (function (param) {
                                  Copy_textJs("copyMe");
                                  
                                })
                            }, Templates$LoginForm.clipboard)), React.createElement("div", {
                          className: "p-1 h-full"
                        }, React.createElement("textarea", {
                              className: "w-full h-full outline-none focus:shadow-outline p-4",
                              id: "copyMe",
                              readOnly: true,
                              value: state.jsx
                            })))), Templates$LoginForm.footer);
}

var $$default = Index$default;

exports.defaultText = defaultText;
exports.initialState = initialState;
exports.reducer = reducer;
exports.copy_text = copy_text;
exports.copyOutput = copyOutput;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* initialState Not a pure module */
