// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function setInputState(setter, evt) {
  var v = evt.target.value;
  return Curry._1(setter, (function (param) {
                return v;
              }));
}

function Login$default(Props) {
  var match = React.useState((function () {
          return "notgood";
        }));
  var email_set = match[1];
  var match$1 = React.useState((function () {
          return "no";
        }));
  var password_set = match$1[1];
  return React.createElement("div", {
              className: "min-h-screen bg-white flex"
            }, React.createElement("div", {
                  className: "flex-1 flex flex-col justify-center py-12 px-4 sm:px-6 lg:flex-none lg:px-20 xl:px-24"
                }, React.createElement("div", {
                      className: "mx-auto w-full max-w-sm"
                    }, React.createElement("div", undefined, React.createElement("h2", {
                              className: "mt-6 text-3xl leading-9 font-extrabold text-gray-900"
                            }, "Sign in to your account")), React.createElement("div", {
                          className: "mt-8"
                        }, React.createElement("div", {
                              className: "mt-6"
                            }, React.createElement("form", {
                                  action: "#"
                                }, React.createElement("div", undefined, React.createElement("label", {
                                          className: "block text-sm font-medium leading-5 text-gray-700",
                                          htmlFor: "email"
                                        }, "Email address"), React.createElement("div", {
                                          className: "mt-1 rounded-md shadow-sm"
                                        }, React.createElement("input", {
                                              className: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5",
                                              id: "email",
                                              type: "email",
                                              value: match[0],
                                              onChange: (function (param) {
                                                  return setInputState(email_set, param);
                                                })
                                            })), React.createElement("div", {
                                          className: "mt-2 text-red-500 text-sm"
                                        }, "Sorry, email is wrong")), React.createElement("div", {
                                      className: "mt-6"
                                    }, React.createElement("label", {
                                          className: "block text-sm font-medium leading-5 text-gray-700",
                                          htmlFor: "password"
                                        }, "Password"), React.createElement("div", {
                                          className: "mt-1 rounded-md shadow-sm"
                                        }, React.createElement("input", {
                                              className: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5",
                                              id: "password",
                                              type: "password",
                                              value: match$1[0],
                                              onChange: (function (param) {
                                                  return setInputState(password_set, param);
                                                })
                                            })), React.createElement("div", {
                                          className: "mt-2 text-red-500 text-sm"
                                        }, "Sorry, password is wrong")), React.createElement("div", {
                                      className: "mt-6"
                                    }, React.createElement("span", {
                                          className: "block w-full rounded-md shadow-sm"
                                        }, React.createElement("button", {
                                              className: "w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out",
                                              type: "submit"
                                            }, "Sign in")))))))), React.createElement("div", {
                  className: "hidden lg:block relative w-0 flex-1"
                }, React.createElement("img", {
                      className: "absolute inset-0 h-full w-full object-cover",
                      alt: "",
                      src: "https://images.unsplash.com/photo-1520853504280-249b72dc947c?ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80"
                    })));
}

var $$default = Login$default;

exports.setInputState = setInputState;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
