// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Ast_operationsJs = require("./ast_operations.js");

function transform(prim, prim$1) {
  return Ast_operationsJs(prim, prim$1);
}

function convert(name, source) {
  return Ast_operationsJs(name, source);
}

exports.transform = transform;
exports.convert = convert;
/* ./ast_operations.js Not a pure module */
