// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var header = React.createElement("div", {
      className: "flex items-center justify-between p-6 shadow mb-6 bg-white"
    }, React.createElement("div", {
          className: "flex-1 min-w-0"
        }, React.createElement("h2", {
              className: "text-2xl font-bold leading-7 text-gray-700 sm:text-3xl sm:leading-9 sm:truncate"
            }, "HTML to Reason")), React.createElement("div", {
          className: "text-sm text-gray-400"
        }, "Brought to you by  ", React.createElement("a", {
              className: "text-blue-400",
              href: "https://mrmurphy.dev/",
              target: "_blank"
            }, "Murphy Randle")));

var footer = React.createElement("div", {
      className: "bg-gray-400 text-gray-600 p-6 py-6 text-xs"
    }, React.createElement("div", {
          className: "grid grid-cols-2 gap-4"
        }, React.createElement("div", undefined, React.createElement("h2", {
                  className: "font-semibold text-lg mb-2 text-gray-700"
                }, "What this does"), React.createElement("ul", undefined, React.createElement("li", undefined, "Replaces 'class=' with 'className='"), React.createElement("li", undefined, "Replaces 'type=' with 'type_='"), React.createElement("li", undefined, "Replaces 'for=' with 'htmlFor='"), React.createElement("li", undefined, "Converts attributes to CamelCase"), React.createElement("li", undefined, "Wraps text in quotes and ->string"), React.createElement("li", undefined, "Converts HTML comments to Reason comments"), React.createElement("li", undefined, "Closes self-closing attributes"))), React.createElement("div", undefined, React.createElement("h2", {
                  className: "font-semibold text-lg mb-2 text-gray-700"
                }, "Made Possible By"), React.createElement("ul", undefined, React.createElement("li", {
                      className: "underline"
                    }, React.createElement("a", {
                          href: "https://github.com/rehypejs/rehype",
                          target: "_blank"
                        }, "Unified and rehype")), React.createElement("li", {
                      className: "underline"
                    }, React.createElement("a", {
                          href: "https://feathericons.com/?query=copy",
                          target: "_blank"
                        }, "Feather Icons")), React.createElement("li", {
                      className: "underline"
                    }, React.createElement("a", {
                          href: "https://nextjs.org/",
                          target: "_blank"
                        }, "Next.js")), React.createElement("li", {
                      className: "underline"
                    }, React.createElement("a", {
                          href: "https://www.npmjs.com/package/lodash.camelcase",
                          target: "_blank"
                        }, "Lodash.camelcase")), React.createElement("li", {
                      className: "underline"
                    }, React.createElement("a", {
                          href: "https://tailwindui.com",
                          target: "_blank"
                        }, "Tailwind & Tailwind UI")), React.createElement("li", {
                      className: "underline"
                    }, React.createElement("a", {
                          href: "https://regexr.com/",
                          target: "_blank"
                        }, "Regexr")), React.createElement("li", {
                      className: "underline"
                    }, React.createElement("a", {
                          href: "https://netlify.com/",
                          target: "_blank"
                        }, "Netlify")), React.createElement("li", {
                      className: "underline"
                    }, React.createElement("a", {
                          href: "https://reasonml.github.io/reason-react/",
                          target: "_blank"
                        }, "Reason React")), React.createElement("li", {
                      className: ""
                    }, "And many more, as I'm sure you know")))));

var clipboard = React.createElement("svg", {
      className: "stroke-current",
      height: "24",
      width: "24",
      fill: "none",
      stroke: "currentColor",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "2",
      viewBox: "0 0 24 24",
      xmlns: "http://www.w3.org/2000/svg"
    }, React.createElement("path", {
          d: "M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"
        }), React.createElement("rect", {
          height: "4",
          width: "8",
          rx: "1",
          ry: "1",
          x: "8",
          y: "2"
        }));

exports.header = header;
exports.footer = footer;
exports.clipboard = clipboard;
/* header Not a pure module */
