// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Ast_operationsJs = require("./ast_operations.js");
var HtmlConverter$LoginForm = require("./HtmlConverter.bs.js");

var htmlTestCases = [];

var svgTestCases = [];

var testCaseFiles = Belt_Array.concat(htmlTestCases, svgTestCases);

var testCases = Belt_Array.map(testCaseFiles, (function (filename) {
        return /* tuple */[
                filename,
                Fs.readFileSync("./testCases/" + filename, "utf8")
              ];
      }));

function test(param) {
  var testShellContent = {
    contents: "set -e;\necho 'RUNNING REFMT TESTS';\necho;\necho;"
  };
  Belt_Array.forEach(testCases, (function (testCase) {
          var name = testCase[0];
          var filename = "/tmp/" + (String(name) + ".re");
          console.log("Appending test case: ", filename);
          testShellContent.contents = testShellContent.contents + ("\n" + ("head " + (String(filename) + ("; /Users/s/.esy/3_______________________________________________________________________/i/opam__s__reason-7d161d4c/bin/refmt --in-place " + (String(filename) + ";\n             ")))));
          var result = HtmlConverter$LoginForm.convert(name, testCase[1]);
          Fs.writeFileSync(filename, "/* Original:\n\n*/\n\nlet result = (<> " + (String(result) + " </>)\n\n"));
          
        }));
  Fs.writeFileSync("./test.sh", testShellContent.contents);
  
}

test(undefined);

exports.htmlTestCases = htmlTestCases;
exports.svgTestCases = svgTestCases;
exports.testCaseFiles = testCaseFiles;
exports.testCases = testCases;
exports.test = test;
/*  Not a pure module */
